name: Build and Deploy - Cloudflare Pages
on:
  workflow_call:
    inputs:
      CLOUDFLARE_ENV:
        required: false
        type: string
        default: ${{ contains(github.ref, 'main') && 'prod' || contains(github.ref, 'staging') && 'staging' || 'dev'}}
      NODE_ENV:
        required: false
        type: string
        default: ${{ contains(github.ref, 'main') && 'production' || contains(github.ref, 'staging') && 'staging' || 'development'}}
      APP_NAME:
        required: true
        type: string

jobs:
  setup-build-publish-deploy:
    name: Publish to Cloudflare Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Setup Yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build Production Bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build:${{ inputs.NODE_ENV }} --filter=${{ inputs.APP_NAME }}

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_API_TOKEN }}
          accountId: d8803c6a6253e9267bf1000ca69db18d
          projectName: ${{ inputs.CLOUDFLARE_ENV }}-${{ inputs.APP_NAME }}
          directory: apps/${{ inputs.APP_NAME }}/dist
          branch: main